/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Bridge */

#ifndef _Included_Bridge
#define _Included_Bridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Bridge
 * Method:    DownloadFile
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Bridge_DownloadFile
  (JNIEnv *, jobject, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
