/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DownloadThread */

#ifndef _Included_DownloadThread
#define _Included_DownloadThread
#ifdef __cplusplus
extern "C" {
#endif
#undef DownloadThread_MIN_PRIORITY
#define DownloadThread_MIN_PRIORITY 1L
#undef DownloadThread_NORM_PRIORITY
#define DownloadThread_NORM_PRIORITY 5L
#undef DownloadThread_MAX_PRIORITY
#define DownloadThread_MAX_PRIORITY 10L
/*
 * Class:     DownloadThread
 * Method:    DownloadFile
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_DownloadThread_DownloadFile
  (JNIEnv *, jobject, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
