/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sample */

#ifndef _Included_sample
#define _Included_sample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sample
 * Method:    intMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_sample_intMethod
  (JNIEnv *, jobject, jint);

/*
 * Class:     sample
 * Method:    booleanMethod
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_sample_booleanMethod
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     sample
 * Method:    stringMethod
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sample_stringMethod
  (JNIEnv *, jobject, jstring);

/*
 * Class:     sample
 * Method:    intArrayMethod
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_sample_intArrayMethod
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
